"""
FinResearch AI - Gradio Interface
Multi-agent financial research system with interactive UI.
"""

import gradio as gr
import json
import os
import tempfile
from datetime import datetime
from agents.manager_agent import ManagerAgent
from config.settings import get_settings


# Initialize the Manager Agent
manager = ManagerAgent()


def conduct_research(ticker: str, investor_mode: str = "Neutral") -> tuple:
    """
    Main research function called by Gradio interface.

    Args:
        ticker: Stock ticker symbol
        investor_mode: Tone of the report

    Returns:
        Tuple of (executive_summary, financial_indicators, news_sentiment,
                 bull_case, bear_case, final_perspective, full_report_md, full_report_json, status)
    """
    if not ticker:
        error_msg = "Please enter a stock ticker symbol"
        return (error_msg, "", "", "", "", "", "", "", error_msg)

    ticker = ticker.upper().strip()

    try:
        # Convert investor mode to lowercase for processing
        mode = investor_mode.lower()

        # Run the research workflow
        result = manager.conduct_research(ticker, investor_mode=mode, parallel=True)

        if not result['success']:
            error_msg = result.get('error', 'Unknown error occurred')
            return (error_msg, "", "", "", "", "", "", "", error_msg)

        # Extract report sections
        report = result['report']

        executive_summary = report.get('executive_summary', 'N/A')
        company_snapshot = report.get('company_snapshot', 'N/A')
        financial_indicators = f"{company_snapshot}\n\n{report.get('financial_indicators', 'N/A')}"
        news_sentiment = report.get('news_sentiment', 'N/A')
        bull_case = report.get('bull_case', 'N/A')
        bear_case = report.get('bear_case', 'N/A')
        final_perspective = report.get('final_perspective', 'N/A')

        # Generate full markdown report
        full_report_md = generate_markdown_report(report)

        # Generate JSON report
        full_report_json = json.dumps(report, indent=2)

        # Status message
        quality_check = result.get('quality_check', {})
        if quality_check.get('passed'):
            status = f"✅ Research completed successfully for {ticker}"
        else:
            issues = quality_check.get('issues', [])
            status = f"⚠️ Research completed with warnings:\n" + "\n".join([f"- {issue}" for issue in issues])

        return (
            executive_summary,
            financial_indicators,
            news_sentiment,
            bull_case,
            bear_case,
            final_perspective,
            full_report_md,
            full_report_json,
            status
        )

    except Exception as e:
        error_msg = f"❌ Error: {str(e)}"
        return (error_msg, "", "", "", "", "", "", "", error_msg)


def generate_markdown_report(report: dict) -> str:
    """Generate a complete markdown report."""
    md = f"""# Financial Research Report: {report.get('ticker', 'N/A')}

**Generated:** {report.get('generated_date', 'N/A')}
**Investor Mode:** {report.get('investor_mode', 'neutral').title()}

---

## Executive Summary

{report.get('executive_summary', 'N/A')}

---

## Company Snapshot

{report.get('company_snapshot', 'N/A')}

---

## Key Financial Indicators

{report.get('financial_indicators', 'N/A')}

---

## Recent News & Sentiment

{report.get('news_sentiment', 'N/A')}

---

## Opportunities (Bull Case)

{report.get('bull_case', 'N/A')}

---

## Risks (Bear Case)

{report.get('bear_case', 'N/A')}

---

## Final Perspective

{report.get('final_perspective', 'N/A')}

---

### Disclaimer

This report is generated by an AI-powered multi-agent system and should not be considered as financial advice. Always conduct your own research and consult with a qualified financial advisor before making investment decisions. Past performance does not guarantee future results.

---

*Generated by FinResearch AI*
"""
    return md


def clear_outputs():
    """Clear all outputs."""
    return ("", "", "", "", "", "", "", "", "")


# Create Gradio interface
with gr.Blocks(title="FinResearch AI") as app:
    gr.Markdown("""
    # 🔴 FinResearch AI - Advanced Multi-Agent System

    A production-grade financial research system powered by specialized AI agents that autonomously gather data,
    analyze metrics, and generate comprehensive investment reports.

    **Features:**
    - 🔍 Real-time news and sentiment analysis
    - 📊 Comprehensive financial ratio computation
    - 💾 Shared vector memory for context persistence
    - 📝 Professional investor-style reports
    """)

    with gr.Row():
        with gr.Column(scale=2):
            ticker_input = gr.Textbox(
                label="Stock Ticker",
                placeholder="e.g., AAPL, TSLA, MSFT",
                info="Enter a valid stock ticker symbol"
            )

        with gr.Column(scale=1):
            mode_input = gr.Radio(
                choices=["Neutral", "Bullish", "Bearish"],
                value="Neutral",
                label="Investor Mode",
                info="Report tone and perspective"
            )

    with gr.Row():
        submit_btn = gr.Button("🚀 Generate Report", variant="primary", size="lg")
        clear_btn = gr.Button("🗑️ Clear", variant="secondary")

    status_output = gr.Textbox(label="Status", interactive=False, lines=2)

    with gr.Tabs() as tabs:
        with gr.Tab("📋 Executive Summary"):
            executive_summary_output = gr.Markdown()

        with gr.Tab("📊 Financial Indicators"):
            financial_indicators_output = gr.Markdown()

        with gr.Tab("📰 News & Sentiment"):
            news_sentiment_output = gr.Markdown()

        with gr.Tab("📈 Bull Case"):
            bull_case_output = gr.Markdown()

        with gr.Tab("📉 Bear Case"):
            bear_case_output = gr.Markdown()

        with gr.Tab("🎯 Final Perspective"):
            final_perspective_output = gr.Markdown()

        with gr.Tab("📄 Full Report (Markdown)"):
            with gr.Row():
                download_md_btn = gr.DownloadButton(
                    label="📥 Download Markdown Report",
                    variant="primary"
                )
            full_report_md_output = gr.Textbox(
                label="Full Markdown Report",
                lines=30,
                max_lines=50,
                interactive=False
            )

        with gr.Tab("💾 Full Report (JSON)"):
            with gr.Row():
                download_json_btn = gr.DownloadButton(
                    label="📥 Download JSON Report",
                    variant="primary"
                )
            full_report_json_output = gr.Code(
                label="Full JSON Report",
                language="json",
                lines=30,
                interactive=False
            )

    # Event handlers
    submit_btn.click(
        fn=conduct_research,
        inputs=[ticker_input, mode_input],
        outputs=[
            executive_summary_output,
            financial_indicators_output,
            news_sentiment_output,
            bull_case_output,
            bear_case_output,
            final_perspective_output,
            full_report_md_output,
            full_report_json_output,
            status_output
        ]
    )

    clear_btn.click(
        fn=clear_outputs,
        outputs=[
            executive_summary_output,
            financial_indicators_output,
            news_sentiment_output,
            bull_case_output,
            bear_case_output,
            final_perspective_output,
            full_report_md_output,
            full_report_json_output,
            status_output
        ]
    )

    # Download handlers
    def prepare_md_download(md_content):
        if md_content:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"financial_report_{timestamp}.md"
            temp_file = os.path.join(tempfile.gettempdir(), filename)
            with open(temp_file, 'w', encoding='utf-8') as f:
                f.write(md_content)
            return temp_file
        return None

    def prepare_json_download(json_content):
        if json_content:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"financial_report_{timestamp}.json"
            temp_file = os.path.join(tempfile.gettempdir(), filename)
            with open(temp_file, 'w', encoding='utf-8') as f:
                f.write(json_content)
            return temp_file
        return None

    download_md_btn.click(
        fn=prepare_md_download,
        inputs=[full_report_md_output],
        outputs=[download_md_btn]
    )

    download_json_btn.click(
        fn=prepare_json_download,
        inputs=[full_report_json_output],
        outputs=[download_json_btn]
    )

    gr.Markdown("""
    ---
    ### About FinResearch AI

    This system uses a multi-agent architecture:
    - **Manager Agent**: Orchestrates the workflow
    - **Researcher Agent**: Gathers news and analyzes sentiment
    - **Financial Analyst Agent**: Computes ratios and metrics
    - **Reporting Agent**: Synthesizes findings into reports

    All agents share a vector memory (ChromaDB) for efficient context retrieval.

    **Disclaimer:** This tool provides AI-generated financial analysis for informational purposes only.
    It is not financial advice. Always consult with a qualified financial advisor before making investment decisions.
    """)


if __name__ == "__main__":
    # Validate settings before starting
    try:
        settings = get_settings()
        print("[OK] Configuration loaded successfully")
        print(f"   - OpenAI Model: {settings.openai_model}")
        print(f"   - Vector DB Path: {settings.vector_db_path}")
        print(f"   - Search API: {'Tavily' if settings.tavily_api_key else 'SerpAPI' if settings.serpapi_api_key else 'Fallback'}")
        print("\nStarting FinResearch AI...")
        app.launch(share=False, server_port=7860)
    except Exception as e:
        print(f"[ERROR] Error: {str(e)}")
        print("Please check your .env file and ensure all required API keys are set.")
