"""
Formatting utilities for financial data and reports.
"""

from typing import Dict, Any, List
import json


def format_financial_data(data: Dict[str, Any]) -> str:
    """
    Format financial data into a readable string.

    Args:
        data: Dictionary containing financial metrics

    Returns:
        Formatted string representation
    """
    if 'error' in data:
        return f"Error: {data['error']}"

    output = []
    output.append(f"Company: {data.get('company_name', 'N/A')} ({data.get('ticker', 'N/A')})")
    output.append(f"Sector: {data.get('sector', 'N/A')} | Industry: {data.get('industry', 'N/A')}")
    output.append(f"\nCurrent Price: ${data.get('current_price', 0):.2f}")
    output.append(f"Market Cap: ${data.get('market_cap', 0):,.0f}")

    output.append("\nPrice Performance:")
    price_changes = data.get('price_changes', {})
    output.append(f"  1 Day: {price_changes.get('1_day', 0):+.2f}%")
    output.append(f"  1 Week: {price_changes.get('1_week', 0):+.2f}%")
    output.append(f"  1 Month: {price_changes.get('1_month', 0):+.2f}%")
    output.append(f"  1 Year: {price_changes.get('1_year', 0):+.2f}%")

    output.append("\nValuation Metrics:")
    output.append(f"  P/E Ratio: {data.get('pe_ratio', 0):.2f}")
    output.append(f"  Forward P/E: {data.get('forward_pe', 0):.2f}")
    output.append(f"  PEG Ratio: {data.get('peg_ratio', 0):.2f}")
    output.append(f"  Price to Book: {data.get('price_to_book', 0):.2f}")

    output.append("\nFinancial Health:")
    output.append(f"  Debt to Equity: {data.get('debt_to_equity', 0):.2f}")
    output.append(f"  Current Ratio: {data.get('current_ratio', 0):.2f}")
    output.append(f"  ROE: {data.get('roe', 0):.2%}")

    output.append("\nGrowth Metrics:")
    output.append(f"  Revenue Growth: {data.get('revenue_growth', 0):.2%}")
    output.append(f"  Earnings Growth: {data.get('earnings_growth', 0):.2%}")
    output.append(f"  EPS: ${data.get('eps', 0):.2f}")

    output.append("\nRisk Indicators:")
    output.append(f"  Volatility: {data.get('volatility', 0):.2f}%")
    output.append(f"  Beta: {data.get('beta', 0):.2f}")

    return "\n".join(output)


def format_news_results(news: List[Dict[str, Any]]) -> str:
    """
    Format news results into a readable string.

    Args:
        news: List of news articles

    Returns:
        Formatted string representation
    """
    if not news:
        return "No news articles found."

    output = []
    for i, article in enumerate(news, 1):
        output.append(f"{i}. {article.get('title', 'N/A')}")
        output.append(f"   Date: {article.get('published_date', 'N/A')}")
        output.append(f"   {article.get('snippet', 'No description available.')}")
        output.append(f"   URL: {article.get('url', 'N/A')}")
        output.append("")

    return "\n".join(output)


def format_report(report_data: Dict[str, Any], format_type: str = "markdown") -> str:
    """
    Format a complete financial report.

    Args:
        report_data: Dictionary containing all report sections
        format_type: Output format ('markdown' or 'json')

    Returns:
        Formatted report string
    """
    if format_type == "json":
        return json.dumps(report_data, indent=2)

    # Markdown format
    output = []
    output.append(f"# Financial Research Report: {report_data.get('ticker', 'N/A')}")
    output.append(f"\n**Generated:** {report_data.get('generated_date', 'N/A')}")
    output.append(f"\n---\n")

    # Executive Summary
    output.append("## Executive Summary")
    output.append(report_data.get('executive_summary', 'N/A'))
    output.append("")

    # Company Snapshot
    output.append("## Company Snapshot")
    output.append(report_data.get('company_snapshot', 'N/A'))
    output.append("")

    # Key Financial Indicators
    output.append("## Key Financial Indicators")
    output.append(report_data.get('financial_indicators', 'N/A'))
    output.append("")

    # Recent News & Sentiment
    output.append("## Recent News & Sentiment")
    output.append(report_data.get('news_sentiment', 'N/A'))
    output.append("")

    # Bull Case
    output.append("## Opportunities (Bull Case)")
    output.append(report_data.get('bull_case', 'N/A'))
    output.append("")

    # Bear Case
    output.append("## Risks (Bear Case)")
    output.append(report_data.get('bear_case', 'N/A'))
    output.append("")

    # Final Perspective
    output.append("## Final Perspective")
    output.append(report_data.get('final_perspective', 'N/A'))
    output.append("")

    # Disclaimer
    output.append("---")
    output.append("### Disclaimer")
    output.append("This report is generated by an AI system and should not be considered as financial advice. "
                  "Always conduct your own research and consult with a qualified financial advisor before making "
                  "investment decisions.")

    return "\n".join(output)


def format_metric_analysis(metrics: Dict[str, Any]) -> str:
    """
    Format metric analysis with interpretations.

    Args:
        metrics: Dictionary of financial metrics

    Returns:
        Formatted analysis string
    """
    output = []

    # P/E Ratio Analysis
    pe_ratio = metrics.get('pe_ratio', 0)
    if pe_ratio > 0:
        if pe_ratio < 15:
            pe_analysis = "Low (potentially undervalued or slow growth)"
        elif pe_ratio < 25:
            pe_analysis = "Moderate (fairly valued)"
        else:
            pe_analysis = "High (premium valuation or high growth expectations)"
        output.append(f"P/E Ratio ({pe_ratio:.2f}): {pe_analysis}")

    # Debt to Equity Analysis
    de_ratio = metrics.get('debt_to_equity', 0)
    if de_ratio > 0:
        if de_ratio < 0.5:
            de_analysis = "Conservative (low leverage)"
        elif de_ratio < 1.0:
            de_analysis = "Moderate (balanced leverage)"
        else:
            de_analysis = "High (aggressive leverage, higher risk)"
        output.append(f"Debt/Equity ({de_ratio:.2f}): {de_analysis}")

    # ROE Analysis
    roe = metrics.get('roe', 0)
    if roe > 0:
        if roe < 0.10:
            roe_analysis = "Below average profitability"
        elif roe < 0.20:
            roe_analysis = "Good profitability"
        else:
            roe_analysis = "Excellent profitability"
        output.append(f"Return on Equity ({roe:.2%}): {roe_analysis}")

    # Volatility Analysis
    volatility = metrics.get('volatility', 0)
    if volatility > 0:
        if volatility < 20:
            vol_analysis = "Low volatility (stable)"
        elif volatility < 40:
            vol_analysis = "Moderate volatility"
        else:
            vol_analysis = "High volatility (risky)"
        output.append(f"Volatility ({volatility:.2f}%): {vol_analysis}")

    return "\n".join(output)
